### ISSUE TITLE
[Bug] Parsing error of evaluation_perspective

### ISSUE THREAD

**Issue by smartie2076** [rl-institut/offgridders#140]
The parameter `evaluation_perspective` seems to be incorrectly parsed from the input file:

```
11:13:40-INFO-Following project locations are evaluated: test_site
--- Logging error ---
Traceback (most recent call last):
  File "D:\PycharmProjects\offgridders\win_env\lib\logging\__init__.py", line 1126, in emit
    msg = self.format(record)
  File "D:\PycharmProjects\offgridders\win_env\lib\logging\__init__.py", line 966, in format
    return fmt.format(record)
  File "D:\PycharmProjects\offgridders\win_env\lib\logging\__init__.py", line 690, in format
    record.message = record.getMessage()
  File "D:\PycharmProjects\offgridders\win_env\lib\logging\__init__.py", line 443, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "Offgridders.py", line 293, in <module>
    main()
  File "Offgridders.py", line 89, in main
    ) = excel_template.process_excel_file(input_excel_file)
  File "D:\PycharmProjects\offgridders\src\B_read_from_files.py", line 119, in process_excel_file
    case_definitions = get_case_definitions(input_excel_file, sheet_case_definitions)
  File "D:\PycharmProjects\offgridders\src\B_read_from_files.py", line 259, in get_case_definitions
    case_definitions[case][EVALUATION_PERSPECTIVE],
Message: "Parameter evaluation_perspective has to be either 'AC_system' or 'DC_system', but is "
Arguments: ('AC_system',)
```

We need to figure out on which branches this happens.

**Comment by smartie2076** [comment]
This seems to be connected to #141.
