### ISSUE TITLE
Multiple problems with installing and running OffGridders v4.6

### ISSUE THREAD

**Issue by mahendrark** [rl-institut/offgridders#142]
I tried installing offgridders v4.6 in Linux Xubuntu 18.02. I found the following problems:

1. It took more than 1/2 hour to install all the packages when I do a `pip install -r requirements.txt` in the terminal. 

It gets stuck at the following line:

```
Building wheels for collected packages: pandas
  Building wheel for pandas (setup.py) ... \
```
I did a workaround by installing manually all the packages. 

2. I ran this command and ran into the error:

`python Offgridders.py ./inputs/test_input_template.xlsx`

Error is:

```
Traceback (most recent call last):
  File "Offgridders.py", line 14, in <module>
    import src.A1_general_functions as helpers
  File "/home/mr/Projects/ves/offgridders-4.6/src/A1_general_functions.py", line 5, in <module>
    import pandas as pd
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/pandas/_libs/__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "__init__.pxd", line 872, in init pandas._libs.tslib
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
(ves_work) (base) mr@nb-24admin:~/Projects/ves/offgridders-4.6$ python Offgridders.py ./inputs/test_input_template.xlsx
Traceback (most recent call last):
  File "Offgridders.py", line 14, in <module>
    import src.A1_general_functions as helpers
  File "/home/mr/Projects/ves/offgridders-4.6/src/A1_general_functions.py", line 5, in <module>
    import pandas as pd
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/pandas/_libs/__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "__init__.pxd", line 872, in init pandas._libs.tslib
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```

**Comment by mahendrark** [comment]
I solved the issue in point # 2 above by running the below command from this [issue](https://github.com/automl/auto-sklearn/issues/621) 

`pip install --upgrade numpy==1.16.0
`

`python Offgridders.py ./inputs/test_input_template.xlsx`

Now I ran into the following error when I executed above command:

```
Traceback (most recent call last):
  File "Offgridders.py", line 14, in <module>
    import src.A1_general_functions as helpers
  File "/home/mr/Projects/ves/offgridders-4.6/src/A1_general_functions.py", line 21, in <module>
    import matplotlib.pyplot as plt
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/matplotlib/__init__.py", line 1111, in <module>
    rcParamsOrig = RcParams(rcParams.copy())
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/matplotlib/__init__.py", line 891, in __getitem__
    from matplotlib import pyplot as plt
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/matplotlib/colorbar.py", line 40, in <module>
    import matplotlib._constrained_layout as constrained_layout
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/matplotlib/_constrained_layout.py", line 52, in <module>
    from matplotlib.legend import Legend
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/matplotlib/legend.py", line 43, in <module>
    from matplotlib.offsetbox import HPacker, VPacker, TextArea, DrawingArea
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 33, in <module>
    from matplotlib.image import BboxImage
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/matplotlib/image.py", line 19, in <module>
    from matplotlib.backend_bases import FigureCanvasBase
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 46, in <module>
    from matplotlib import (
ImportError: cannot import name 'get_backend' from partially initialized module 'matplotlib' (most likely due to a circular import) (/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/matplotlib/__init__.py)
```

**Comment by mahendrark** [comment]
Uninstalled and reinstalled matplotlib.

Ran OffGridders.py again and ran into this error:
```

Traceback (most recent call last):
  File "Offgridders.py", line 20, in <module>
    import src.G0_oemof_simulate as oemof_simulate
  File "/home/mr/Projects/ves/offgridders-4.6/src/G0_oemof_simulate.py", line 20, in <module>
    import src.G1_oemof_create_model as oemof_model
  File "/home/mr/Projects/ves/offgridders-4.6/src/G1_oemof_create_model.py", line 4, in <module>
    from oemof.solph import processing
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/oemof/solph/processing.py", line 22, in <module>
    from oemof.solph.helpers import flatten
  File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/oemof/solph/helpers.py", line 24, in <module>
    from oemof.solph.plumbing import sequence
ModuleNotFoundError: No module named 'oemof.solph.plumbing'

```

**Comment by mahendrark** [comment]
Documenting issues so as to help others in case they encounter such issues

**Comment by mahendrark** [comment]
> Uninstalled and reinstalled matplotlib.
> 
> Ran OffGridders.py again and ran into this error:
> 
> ```
> 
> Traceback (most recent call last):
>   File "Offgridders.py", line 20, in <module>
>     import src.G0_oemof_simulate as oemof_simulate
>   File "/home/mr/Projects/ves/offgridders-4.6/src/G0_oemof_simulate.py", line 20, in <module>
>     import src.G1_oemof_create_model as oemof_model
>   File "/home/mr/Projects/ves/offgridders-4.6/src/G1_oemof_create_model.py", line 4, in <module>
>     from oemof.solph import processing
>   File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/oemof/solph/processing.py", line 22, in <module>
>     from oemof.solph.helpers import flatten
>   File "/home/mr/Projects/dev_envs/ves_work/lib/python3.8/site-packages/oemof/solph/helpers.py", line 24, in <module>
>     from oemof.solph.plumbing import sequence
> ModuleNotFoundError: No module named 'oemof.solph.plumbing'
> ```

Same error arises with Master version

**Comment by mahendrark** [comment]
Tried with my Windows 10 laptop now

Ran into the following installation problems:

1. I created an environment using conda prompt and then tried to do `pip install -r requirements.txt` and got the following error:

```
ERROR: To modify pip, please run the following command:
C:\Users\Newuser\Anaconda3\envs\ves_work\python.exe -m pip install -r requirements.txt
You are using pip version 10.0.1, however version 20.3b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
So I ran `python -m pip install --upgrade pip` and upgraded pip. Then ran into the following error when I tried `pip install -r requirements.txt`:

```
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting appdirs==1.4.3
  Using cached appdirs-1.4.3-py2.py3-none-any.whl (12 kB)
Collecting chardet==3.0.4
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting cycler==0.10.0
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
ERROR: Could not find a version that satisfies the requirement black==19.10b0 (from -r requirements.txt (line 4)) (from versions: none)
ERROR: No matching distribution found for black==19.10b0 (from -r requirements.txt (line 4))
```

**Comment by mahendrark** [comment]
Tried installation from within PyCharm and got this error:

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed


```
Building graph of deps:   0%|          | 0/4 [00:00<?, ?it/s]
Examining decorator==4.3.0:   0%|          | 0/4 [00:00<?, ?it/s]
Examining @/win-64::__archspec==1=x86_64:  25%|##5       | 1/4 [00:00<00:00, 100.71it/s]
Examining @/win-64::__win==0=0:  50%|#####     | 2/4 [00:00<00:00, 201.42it/s]          
Examining python=3.8:  75%|#######5  | 3/4 [00:00<00:00, 302.13it/s]          
                                                                    

Determining conflicts:   0%|          | 0/4 [00:00<?, ?it/s]
Examining conflict for decorator python:   0%|          | 0/4 [00:00<?, ?it/s]
                                                                              
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - decorator==4.3.0 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

```

My Python version is 3.5 because I used that to create the environment and running `python --version` tells me that.

**Comment by smartie2076** [comment]
I also tried installing offgridders 4.6 via the following steps:
### Used Windows10 RLI Laptop with Pycharm
### Cloned the git repository `https://github.com/rl-institut/offgridders.git`
![grafik](https://user-images.githubusercontent.com/44204527/98355075-f1f05080-2021-11eb-82a1-ef70df5514ba.png)
![grafik](https://user-images.githubusercontent.com/44204527/98355120-03d1f380-2022-11eb-9572-5eec7aea5cc0.png)

### Created a new `python 3.7` environment using conda (wheel took some time but not more then 5 minutes)
![grafik](https://user-images.githubusercontent.com/44204527/98355159-13e9d300-2022-11eb-94f8-d2a1c9652645.png)
![grafik](https://user-images.githubusercontent.com/44204527/98355222-23691c00-2022-11eb-8ebb-844331f4877c.png)
![grafik](https://user-images.githubusercontent.com/44204527/98355240-2c59ed80-2022-11eb-8699-7ee81bc525c5.png)
![grafik](https://user-images.githubusercontent.com/44204527/98355319-44317180-2022-11eb-8d3e-3433220a40fa.png)

### if necessary: Open new terminal/activate environment by typing `conda activate PATH_TO_ENV`

### Circumvented placing CBC in my `PATH` environments by placing it into the main folder of my repro:
![grafik](https://user-images.githubusercontent.com/44204527/98355828-fd904700-2022-11eb-8c1b-aa8adbc53b87.png)

### Executed `pip install -r requirements.txt`

I also had an isse with the `numpexpr`:
```
Installing collected packages: numexpr, blinker, pytz, pandas, networkx, oemof.network, PyUtilib, ply, Pyomo, oemof.tools, oemof.solph, pip
, scipy, tables, urllib3, wheel, xlrd, xlsxwriter
    Running setup.py install for numexpr ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\PycharmProjects\offgridders_v4.6\env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\M
ARTHA~1.HOF\\AppData\\Local\\Temp\\pip-install-xs1wet2d\\numexpr\\setup.py'"'"'; __file__='"'"'C:\\Users\\MARTHA~1.HOF\\AppData\\Local\\Tem
p\\pip-install-xs1wet2d\\numexpr\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '
"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MARTHA~1.HOF\AppData\Local\Temp\pip-record
-7o1vn30x\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Martha.Hoffmann\Ap
pData\Roaming\Python\Python37\Include\numexpr'
         cwd: C:\Users\MARTHA~1.HOF\AppData\Local\Temp\pip-install-xs1wet2d\numexpr\
    Complete output (40 lines):
    mkl_info:
    D:\PycharmProjects\offgridders_v4.6\env\lib\site-packages\numpy\distutils\system_info.py:707: UserWarning: Specified path /Program File
s (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/lib/intel64 is invalid.
      return self.get_paths(self.section, key)
    D:\PycharmProjects\offgridders_v4.6\env\lib\site-packages\numpy\distutils\system_info.py:707: UserWarning: Specified path /Program File
s (x86)/IntelSWTools/compilers_and_libraries/windows/compiler/lib/intel64 is invalid.
      return self.get_paths(self.section, key)
    D:\PycharmProjects\offgridders_v4.6\env\lib\site-packages\numpy\distutils\system_info.py:716: UserWarning: Specified path /Program File
s (x86)/IntelSWTools/compilers_and_libraries/windows/mkl/include is invalid.
      return self.get_paths(self.section, key)
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_intel_lp64,mkl_intel_thread,mkl_core,libiomp5md not found in []
      NOT AVAILABLE
    
    Warning: Assuming default configuration (numexpr\tests/{setup_tests,setup}.py was not found)running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    building extension "numexpr.interpreter" sources
    build_src: building npy-pkg config files
    running build_py
    copying build\src.win-amd64-3.7\numexpr\__config__.py -> build\lib.win-amd64-3.7\numexpr
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    Missing compiler_cxx fix for MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'numexpr.interpreter' extension
    compiling C sources
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downlo
ads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\PycharmProjects\offgridders_v4.6\env\python.exe' -u -c 'import sys, setuptools, tokenize
; sys.argv[0] = '"'"'C:\\Users\\MARTHA~1.HOF\\AppData\\Local\\Temp\\pip-install-xs1wet2d\\numexpr\\setup.py'"'"'; __file__='"'"'C:\\Users\\
MARTHA~1.HOF\\AppData\\Local\\Temp\\pip-install-xs1wet2d\\numexpr\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f
.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MARTHA~1.
HOF\AppData\Local\Temp\pip-record-7o1vn30x\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-hea
ders 'C:\Users\Martha.Hoffmann\AppData\Roaming\Python\Python37\Include\numexpr' Check the logs for full command output.
```
But when I removed the dependency `numexpr==2.6.8` in the `requirements.txt` file, the installation ran through and installed `numexpr-2.7.1`. Maybe the other version is outdated by now.

### Ran test simulation of my Offgridders (`python Offgridders.py`)

There is still the isse with parsing `(AC System, )` (as described in #140, #141), but that does not mess with the simulation itself, and it runs though:

```
(D:\PycharmProjects\offgridders_v4.6\env) D:\PycharmProjects\offgridders_v4.6>python Offgridders.py
11:47:56-INFO-Path for logging: ./micro_grid_design_logfile.log
11:47:56-INFO-
 Coded by: Martha M. Hoffmann
 Reiner Lemoine Institute (Berlin)


11:47:56-INFO-Performing simulations defined by file "./inputs/test_input_template.xlsx"

11:47:56-INFO-Following project locations are evaluated: test_site
--- Logging error ---
Traceback (most recent call last):
  File "D:\PycharmProjects\offgridders_v4.6\env\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "D:\PycharmProjects\offgridders_v4.6\env\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "D:\PycharmProjects\offgridders_v4.6\env\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "D:\PycharmProjects\offgridders_v4.6\env\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "Offgridders.py", line 293, in <module>
    main()
  File "Offgridders.py", line 89, in main
    ) = excel_template.process_excel_file(input_excel_file)
  File "D:\PycharmProjects\offgridders_v4.6\src\B_read_from_files.py", line 147, in process_excel_file
    case_definitions = get_case_definitions(input_excel_file, sheet_case_definitions)
  File "D:\PycharmProjects\offgridders_v4.6\src\B_read_from_files.py", line 415, in get_case_definitions
    case_definitions[case][EVALUATION_PERSPECTIVE],
Message: "Parameter evaluation_perspective has to be either 'AC_system' or 'DC_system', but is "
Arguments: ('AC_system',)
--- Logging error ---
Traceback (most recent call last):
  File "D:\PycharmProjects\offgridders_v4.6\env\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "D:\PycharmProjects\offgridders_v4.6\env\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "D:\PycharmProjects\offgridders_v4.6\env\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "D:\PycharmProjects\offgridders_v4.6\env\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "Offgridders.py", line 293, in <module>
    main()
  File "Offgridders.py", line 89, in main
    ) = excel_template.process_excel_file(input_excel_file)
  File "D:\PycharmProjects\offgridders_v4.6\src\B_read_from_files.py", line 147, in process_excel_file
    case_definitions = get_case_definitions(input_excel_file, sheet_case_definitions)
  File "D:\PycharmProjects\offgridders_v4.6\src\B_read_from_files.py", line 415, in get_case_definitions
    case_definitions[case][EVALUATION_PERSPECTIVE],
Message: "Parameter evaluation_perspective has to be either 'AC_system' or 'DC_system', but is "
Arguments: ('AC_system',)
[...]
 Overview over results:
  project_site_name                       case pv_cost_investment pv_lifetime     lcoe  res_share
0         test_site               pv-diesel-mg               1000          20  0.28144    0.26629
1         test_site       pv-diesel-storage-mg               1000          20  0.26789    0.41451
2         test_site  pv-wind-storage-diesel-mg               1000          20  0.24887    0.58512
11:48:04-INFO-Performing multicriteria analysis
11:48:06-INFO-Multicriteria analysis was successfully performed

 Warnings or errors might have occurred.
Please check terminal output or saved log-file to make sure they do not influence your simulation results.
```

### Notes:
* @mahendrark rightfully updated `pip` in case that there were issues with the dependencies. 
* @mahendrark you used `python 3.5` as per instructions - I think that may have been a typo. You could try using `python 3.6` or `python 3.7` for your environment.

**Comment by smartie2076** [comment]
Also had issues with my pip version:

```
pip --upgrade

Traceback (most recent call last):
  File "D:\PycharmProjects\offgridders\win_env\Scripts\pip-script.py", line 5, in <mo
dule>
    from pip._internal.main import main
ModuleNotFoundError: No module named 'pip._internal.main'
```

```
python -m pip
 install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e2216903210
0d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.0.2
    Uninstalling pip-19.0.2:
      Successfully uninstalled pip-19.0.2
  Rolling back uninstall of pip
  Moving to c:\users\martha.hoffmann\appdata\roaming\python\python37\scripts\pip.exe
   from C:\Users\MARTHA~1.HOF\AppData\Local\Temp\pip-uninstall-pdl0jeg5\pip.exe
  Moving to c:\users\martha.hoffmann\appdata\roaming\python\python37\scripts\pip3.7.e
xe
   from C:\Users\MARTHA~1.HOF\AppData\Local\Temp\pip-uninstall-pdl0jeg5\pip3.7.exe
  Moving to c:\users\martha.hoffmann\appdata\roaming\python\python37\scripts\pip3.exe

   from C:\Users\MARTHA~1.HOF\AppData\Local\Temp\pip-uninstall-pdl0jeg5\pip3.exe
  Moving to c:\users\martha.hoffmann\appdata\roaming\python\python37\site-packages\pi
p-19.0.2.dist-info\
   from c:\users\martha.hoffmann\appdata\roaming\python\python37\site-packages\~ip-19
.0.2.dist-info
  Moving to c:\users\martha.hoffmann\appdata\roaming\python\python37\site-packages\pi
p\
   from c:\users\martha.hoffmann\appdata\roaming\python\python37\site-packages\~ip
Exception:
Traceback (most recent call last):
  File "C:\Users\Martha.Hoffmann\AppData\Roaming\Python\Python37\site-packages\pip\_i
nternal\cli\base_command.py", line 179, in main
    status = self.run(options, args)
  File "C:\Users\Martha.Hoffmann\AppData\Roaming\Python\Python37\site-packages\pip\_i
nternal\commands\install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "C:\Users\Martha.Hoffmann\AppData\Roaming\Python\Python37\site-packages\pip\_i
nternal\req\__init__.py", line 57, in install_given_reqs
    **kwargs
  File "C:\Users\Martha.Hoffmann\AppData\Roaming\Python\Python37\site-packages\pip\_i
nternal\req\req_install.py", line 913, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "C:\Users\Martha.Hoffmann\AppData\Roaming\Python\Python37\site-packages\pip\_i
nternal\req\req_install.py", line 445, in move_wheel_files
    warn_script_location=warn_script_location,
  File "C:\Users\Martha.Hoffmann\AppData\Roaming\Python\Python37\site-packages\pip\_i
nternal\wheel.py", line 537, in move_wheel_files
    generated.extend(maker.make(spec))
  File "C:\Users\Martha.Hoffmann\AppData\Roaming\Python\Python37\site-packages\pip\_v
endor\distlib\scripts.py", line 405, in make
    self._make_script(entry, filenames, options=options)
  File "C:\Users\Martha.Hoffmann\AppData\Roaming\Python\Python37\site-packages\pip\_v
endor\distlib\scripts.py", line 309, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "C:\Users\Martha.Hoffmann\AppData\Roaming\Python\Python37\site-packages\pip\_v
endor\distlib\scripts.py", line 245, in _write_script
    launcher = self._get_launcher('t')
  File "C:\Users\Martha.Hoffmann\AppData\Roaming\Python\Python37\site-packages\pip\_v
endor\distlib\scripts.py", line 384, in _get_launcher
    result = finder(distlib_package).find(name).bytes
AttributeError: 'NoneType' object has no attribute 'bytes'
You are using pip version 19.0.2, however version 20.3b1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

My pip issues were solved executing

`>python -m pip  install --user --upgrade pip`

This installed `pip-20.2.4`.

**Comment by smartie2076** [comment]
I released a patch for Offgridders and the installation issues: https://github.com/rl-institut/offgridders/releases/tag/v4.6.1
Please let me know if this fixes your (or some of your) issues. Please also note that I updated the installation instructions.
