### ISSUE TITLE
Need to update Pyomo version in requirements.txt for python3.7

### ISSUE THREAD

**Issue by smartie2076** [rl-institut/offgridders#83]
On my windows10 distribution, I am using a python3.7 environment for offgridders. However, this causes the simulation to terminate:

```
Traceback (most recent call last):
  File "Offgridders.py", line 20, in <module>
    import src.G0_oemof_simulate as oemof_simulate
  File "D:\PycharmProjects\offgridders\src\G0_oemof_simulate.py", line 22, in <module>
    import src.G1_oemof_create_model as oemof_model
  File "D:\PycharmProjects\offgridders\src\G1_oemof_create_model.py", line 3, in <module>
    import oemof.solph as solph
  File "D:\PycharmProjects\offgridders\win_env\lib\site-packages\oemof\solph\__init__.py", line 2, in <module>
    from oemof.solph.models import Model
  File "D:\PycharmProjects\offgridders\win_env\lib\site-packages\oemof\solph\models.py", line 11, in <module>
    import pyomo.environ as po
  File "D:\PycharmProjects\offgridders\win_env\lib\site-packages\pyomo\environ\__init__.py", line 100, in <module>
    _import_packages()
  File "D:\PycharmProjects\offgridders\win_env\lib\site-packages\pyomo\environ\__init__.py", line 66, in _import_packages
    _do_import(pname)
  File "D:\PycharmProjects\offgridders\win_env\lib\site-packages\pyomo\environ\__init__.py", line 17, in _do_import
    importlib.import_module(pkg_name)
  File "D:\PycharmProjects\offgridders\win_env\lib\importlib\__init__.py", line 133, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\PycharmProjects\offgridders\win_env\lib\site-packages\pyomo\pysp\__init__.py", line 27, in <module>
    import pyomo.pysp.scenariotree
  File "D:\PycharmProjects\offgridders\win_env\lib\site-packages\pyomo\pysp\scenariotree\__init__.py", line 18, in <module>
    import pyomo.pysp.scenariotree.manager
  File "D:\PycharmProjects\offgridders\win_env\lib\site-packages\pyomo\pysp\scenariotree\manager.py", line 997
    async=False,
        ^
SyntaxError: invalid syntax
```

[Here](https://github.com/Pyomo/pyomo/issues/645) they acknowledge the issue with python3.7. The issue is solved when installing the most recent Pyomo version:

`pip install pyomo==5.7`

Therefore, the `requirements.txt` should be updated.

**Comment by smartie2076** [comment]
The requirements.txt file already defines `Pyomo==5.7.0` as a requirement.
