### ISSUE TITLE
[Bug] Bugs concerning module structure

### ISSUE THREAD

**Issue by smartie2076** [rl-institut/offgridders#85]
I am gathering the bugs I ran into with the current master branch release (v4.2), and which also occur on dev.
This proves that we will need to include more tests so that all usage options are covered.

**Comment by smartie2076** [comment]
###1
```
  File "Offgridders.py", line 78, in main
    settings, parameters_constant_values, parameters_sensitivity, project_site_s
  File "/media/mh/Daten/PycharmProjects/offgridders/src/C_sensitivity_experiments.py", line 72, in get
    project_sites,
  File "/media/mh/Daten/PycharmProjects/offgridders/src/C_sensitivity_experiments.py", line 250, in with_base_case
    universal_parameters, number_of_project_sites = get.universal_parameters(
AttributeError: 'function' object has no attribute 'universal_parameters'
```
Fixed this by calling `get_universal_parameters`.

**Comment by smartie2076** [comment]
```
  File "Offgridders.py", line 80, in main
    settings, parameters_constant_values, parameters_sensitivity, project_site_s
  File "/media/mh/Daten/PycharmProjects/offgridders/src/C_sensitivity_experiments.py", line 72, in get
    project_sites,
  File "/media/mh/Daten/PycharmProjects/offgridders/src/C_sensitivity_experiments.py", line 262, in with_base_case
    ) = get.combinations_around_base(
AttributeError: 'function' object has no attribute 'combinations_around_base'
```
Fixed by renaming function from `combinations_around_base` to `get_combinations_around_base` and calling the latter.

**Comment by smartie2076** [comment]
```
Traceback (most recent call last):
  File "Offgridders.py", line 277, in <module>
    main()
  File "Offgridders.py", line 117, in main
    settings, blackout_experiment_s
  File "/media/mh/Daten/PycharmProjects/offgridders/src/E_blackouts_central_grid.py", line 119, in get_blackouts
    grid_availability_df,
  File "/media/mh/Daten/PycharmProjects/offgridders/src/E_blackouts_central_grid.py", line 184, in availability
    number_of_blackouts = number_of_blackouts(
UnboundLocalError: local variable 'number_of_blackouts' referenced before assignment
```
Related to variable name = function name:
```
        number_of_blackouts = number_of_blackouts(
            settings["max_evaluated_days"], blackout_experiment_s[experiment]
        )
```
Renamed function into `get_number_of_blackouts`
